### ISSUE TITLE
issues with config file

### ISSUE THREAD

**Issue by xunyunliu** [manuzhang/storm-benchmark#4]
Dear authors, 

I was trying to follow the instructions and run this benchmark on my storm cluster. Initially SOL test is used as you suggested, but no matter what I did, the benchmark won't recognize the sol.yaml file as a configuration. I have tried to add the conf directory into the CLASSPATH , put the sol.yaml near the storm.yaml which is located at $STORM_HOME/conf, and even append the contents of sol.yaml at the end of storm.yaml file. Unfortunately none of them works, it keeps telling me that cannot find config file on classpath sol.yaml. I have pasted the error message blow:

![image](https://cloud.githubusercontent.com/assets/9266804/7722576/e4ca27e2-ff24-11e4-8693-f541decd4eea.png)

 
My cluster is a 4 node virtual cluster running storm 0.9.4 on Ubuntu 14.04, and the java version is 1.8. Actually the sol test from yahoo's repository is working properly on this cluster. Could you please give me some advise on how to debug this? Thank your very much.

**Comment by manuzhang** [comment]
Thanks for trying storm-benchmark out.

I've been able to run storm-benchmark over storm (both 0.9.4 and 0.9.3) with the following command 

```bash
 ./stormbench -jar storm-benchmark-0.1.0-jar-with-dependencies.jar -storm /root/apache-storm-0.9.4/bin/storm -conf ./sol.yaml storm.benchmark.tools.Runner storm.benchmark.benchmarks.SOL
```

**Comment by xunyunliu** [comment]
Thank you for your kind reply.

The command I was running is 

`bin/stormbench -storm storm -jar ./target/storm-benchmark-0.1.0-jar-with-dependencies.jar -conf ./conf/sol.yaml -c topology.workers=2 storm.benchmark.tools.Runner storm.benchmark.benchmarks.SOL`

I ran this command from the top-level directory of the Storm benchmark code, before doing that I did't change the location of target jar file (storm-benchmark-0.1.0-jar-with-dependencies.jar)  and the config file (sol.yaml). Am I supposed to move the sol.yaml to somewhere else so that it could become visible to storm?

I also tried your command, which means I have to move the target jar file into the  `bin/ directory` since that the script won't find the package automatically. But it seems that the error is still there. 

Any further suggestions? Thank you very much.

**Comment by manuzhang** [comment]
My jar file is also located under `target` directory. By the way, how do you reference the `storm` script, which can only be run from within a release ?

**Comment by xunyunliu** [comment]
No, I have added the the location of Storm release into the system environment as STORM_HOME , which enables me access `storm` script anywhere. May I ask if you have made any changes in pom.xml file to get it running with 0.9.4 and jdk 1.8? or is it necessary to tweak storm since it is the one who keeps complaining that the configure file cannot be founded?

**Comment by manuzhang** [comment]
I haven't changed anything in `pom.xml`. I just downloaded 0.9.4 from the official site and point `JAVA_HOME` in `storm-env.ini` to jdk1.8 home path. Then I'm able to run storm-benchmark with the command above. No changes made to storm either. Could you try providing the full path of `storm` script like I did ?

**Comment by xunyunliu** [comment]
it seems that the problem is with storm 0.9.4 itself. I just download the source code of 0.9.4, and to my surprise the function `findAndReadConfigFile` in `src-apache-storm-0.9.4/storm-core/src/jvm/backtype/storm/utils` is different from the version that on github and it seems doesn't support reading config from local file system at all. please check the comparison below:

A. ` public static Map findAndReadConfigFile(String name, boolean mustExist)`  from `apache-storm-0.9.4-src.zip `

```
    public static Map findAndReadConfigFile(String name, boolean mustExist) {
        try {
            HashSet<URL> resources = new HashSet<URL>(findResources(name));
            if(resources.isEmpty()) {
                if(mustExist) throw new RuntimeException("Could not find config file on classpath " + name);
                else return new HashMap();
            }
            if(resources.size() > 1) {
                throw new RuntimeException("Found multiple " + name + " resources. You're probably bundling the Storm jars with you
r topology jar. "
                  + resources);
            }
            URL resource = resources.iterator().next();
            Yaml yaml = new Yaml(new SafeConstructor());
            Map ret = null;
            InputStream input = resource.openStream();
            try {
                ret = (Map) yaml.load(new InputStreamReader(input));
            } finally {
                input.close();
            }
            if(ret==null) ret = new HashMap();


            return new HashMap(ret);

        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```
B. ` public static Map findAndReadConfigFile(String name, boolean mustExist)`  from  https://github.com/apache/storm/blob/b4351ede1a89b83888e9e3ace55227e5ae69c78b/storm-core/src/jvm/backtype/storm/utils/Utils.java 

```
 public static Map findAndReadConfigFile(String name, boolean mustExist) {
        InputStream in = null;
        boolean confFileEmpty = false;
        try {
            in = getConfigFileInputStream(name);
            if (null != in) {
                Yaml yaml = new Yaml(new SafeConstructor());
                Map ret = (Map) yaml.load(new InputStreamReader(in));
                if (null != ret) {
                    return new HashMap(ret);
                } else {
                    confFileEmpty = true;
                }
            }

            if (mustExist) {
                if(confFileEmpty)
                    throw new RuntimeException("Config file " + name + " doesn't have any valid storm configs");
                else
                    throw new RuntimeException("Could not find config file on classpath " + name);
            } else {
                return new HashMap();
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            if (null != in) {
                try {
                    in.close();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        }
    }
```

It is easy to find that version A skip the getConfigFileInputStream part and thus is not able to read the config file. So my question is where did you download the storm 0.9.4? Is that from the official release page(which is what I did) or you just download the code from github and build it on your own?

Thank you for your kind reply, your help is greatly appreciated.

**Comment by xunyunliu** [comment]
I also tried your code with storm 0.9.3 release, but unfortunately the error comes out again. I list my process of the environment setting here
1. download the release from a apache mirror, i.e. `http://www.apache.org/dyn/closer.cgi/storm/apache-storm-0.9.4/apache-storm-0.9.4.zip`

2. extract the zip file and change the `conf/storm.yaml` file pointing out the zookeeper address and name of nimbus . 
```
storm.zookeeper.servers:
     - "ubuntuzk"
nimbus.host: "unimbus"
storm.local.dir: "/mnt/storm"
supervisor.slots.ports:
    - 6700
    - 6701
    - 6702
    - 6703
````
3. add JAVA_HOME and STORM_HOME into the PATH. Run `storm nimbus` and `storm ui` on the nimbus node.
4. Do the previous steps again on slave node, but execute `storm supervisor` to start supervisor daemon instead.
5. test with SOL test from yahoo, everything works fine according to the user interface on nimbus.

Is that a correct practice to set up a storm cluster? Your answer is greatly appreciated.

**Comment by manuzhang** [comment]
Are the `B` codes from the 0.9.4-branch ? I downloaded storm jars from the same link as yours. 
Your setup looks fine. Have your checked the printed classpath ? That's what after the `-cp` option. For example, 

```bash
Running: java -client -Dstorm.options= -Dstorm.home=/home/manu/apache-storm-0.9.4 -Dstorm.log.dir=/home/manu/apache-storm-0.9.4/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file=sol.yaml -cp ...:./target/storm-benchmark-0.1.0-jar-with-dependencies.jar:/home/manu/git/storm-benchmark/conf:/home/manu/apache-storm-0.9.4/bin -Dstorm.jar=./target/storm-benchmark-0.1.0-jar-with-dependencies.jar storm.benchmark.tools.Runner storm.benchmark.benchmarks.SOL
```

You can see the directory `/home/manu/git/storm-benchmark/conf` is on the classpath and that's where the `sol.yaml` file could be located by `findResources` function. 

The trick `stormbench` does is to split the `-conf` value into two parts, the directory (DIR) and file itself (FILE). DIR is set to `STORM_CONF_DIR` environment value where `storm` script will pick up and add to the classpath. FILE is set into storm through option `--config` which is finally passed to `findAndReadConfigFile` function. That function will look for FILE on the classpath which already has DIR included.

Hope this helps.

**Comment by xunyunliu** [comment]
I didn't see the `/home/manu/git/storm-benchmark/conf` on my machine, have tried with version 0.9.3 and 0.9.4 and neither of them prints out this directory as a classpath. Maybe there is a small compatibility issue with the `stormbench` script that `STORM_CONF_DIR` has not been correctly configured on my machine.

Thank you. I will go through the `stormbech` script with caution, hope I can fix it. :-)

**Comment by xunyunliu** [comment]
The strange thing is that even though I have manually set up `$STORM_CONF_DIR` in bashrc with the location of `/home/ubuntu/storm-benchmark/conf`, storm is unwilling to add it into the classpath.

**Comment by xunyunliu** [comment]
The error disappeared when I run the benchmark as root user, don't know what is happening but it is good to know it is working!

Thank you.

**Comment by manuzhang** [comment]
Good to know that ;)
